require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'Gemfile.lock'

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/EmptyFile:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/FilePath:
  IgnoreMethods: true
  SpecSuffixOnly: true
