# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 2.7'

group :development, :test do
  gem 'pry', '~> 0.14.1'
  gem 'rspec', '~> 3.11.0'
  gem 'rubocop', '~> 1.33.0', require: false
  gem 'rubocop-performance', '~> 1.14.3', require: false
  gem 'rubocop-rspec', '~> 2.12.1', require: false
end

group :test do
  gem 'simplecov', '~> 0.21.2', require: false
end
